### ISSUE TITLE
PSR7-Request body handling

### ISSUE THREAD

**Issue by trendfischer** [juliangut/spiral#10]
On testing this lib I could not send JSON-Requests to an API. Diving into the code, I discovered, that the PSR7-Request-Handling is not properly implemented. Instead of using the `RequestInterface` to get POST-Parameters or the body, a third parameter `$vars` is used. But this could be set on a PSR7-Request with `withParsedBody($vars)`. For PSR7 compatibility, a `getParsedBody()` should be implemented or better a `(string) $request->getBody()` to allow JSON Requests. The third parameter would be obsolete. The transport `request()`-function would need a `$body` parameter instead of `$vars`.

Since this would be a breaking change to the library, I stopped my testing instead of developing a pull request.

**Comment by juliangut** [comment]
You're right on body handling.

The idea behind transport and transport interface was to decouple it from PSR7 so there is no point on passing Body object to transport's request(), but it really makes sense to parse body on Client to get those vars/body instead of having them on a parameter

Also it would be nice to act according to Content-Type header in order to extract those vars (or json body) and probably set the flags parameter too, what do you think?

All said, this library is in no stable state, it is not 1.x released, so according to SemVer interfaces and behaviour are allowed to change. Feel free to PR

**Comment by trendfischer** [comment]
Ok, the PR #11 is there.

**Comment by juliangut** [comment]
Still pending to be fix

**Comment by juliangut** [comment]
Fixed
