### ISSUE TITLE
Options management

### ISSUE THREAD

**Issue by gsouf** [juliangut/spiral#2]
I noticed that you indnexed all possible options in the [option factory](https://github.com/juliangut/spiral/blob/master/src/Option/OptionFactory.php)

You also created 1 class option class for each curl option, right now you didnt add proxy options and using them leads to exception, when it's actually a valid curl operation.

Theorically that makes things pretty hard to maintain in case of evolution of Curl. Let's imagine that 2 versions of the curl extension offer differents options, the library wont be 100% comptible with both of the 2 versions. 

I recommend to leave the user free to set any option he wants. As you do with [curl info](https://github.com/juliangut/spiral/blob/master/src/Transport/Curl.php#L207)

**Comment by juliangut** [comment]
The idea behind the use of curl option classes was to identify invalid option values through exceptions and allow the user to act in consequence. Having `curl_exec` fail and then review `curl_errno` to identify that the problem was an invalid option value kills me (ie: "Unrecognized parameter value passed via CURLOPT_SSLVERSION")

One thing I want to do though is transform `OptionFactory` into a real factory and get rid of those classes except for `OptionBoolean`, `OptionFile`, `OptionInteger`, `OptionRegex` and `OptionString` so that you should always/only use

```
$option = OptionFactory::build('option-name`, `option-value');
```

This way for a future evolution of cURL with different options they should only be added to the factory itself, reducing the number of classes to work with

The problem with using the `curl_getinfo` approach for options is that curl_getinfo deals with the return of the curl request and will just return `false` on invalid info, not raise any kind of error. So having a map of valid "info" requestable on curl_getinfo is overkill

Finally I assume you need proxy options, they are very easy to add, I'll do it ASAP

**Comment by gsouf** [comment]
Yes, the problem is not adding proxy, the problem is the overall maintabillity of the code.

(as I mentioned in the other ticket I spot a few issues that are ennoying to me. I have to do an intensive usage of curl with PSR7, and I need a simple and solid library for that)

**Comment by juliangut** [comment]
I've made the change on OptionFactory https://github.com/juliangut/spiral/blob/master/src/Option/OptionFactory.php#L249

Now only "known" cURL options will be verified when created, any other CURLOPT_* constant will create a simple value object (\Jgut\Spiral\Option\Option) and go with it
